---
output:
  pdf_document: default
  html_document: default
---
library(readxl)
myDataFrame <- read_excel("C:/MS - Rutgers/Fall_term1/Business Forecasting/W2/Typical_Employee_Survey_Data.xlsx")

# Explore Data Frame
names(myDataFrame)
ncol(myDataFrame)
nrow(myDataFrame)
dim(myDataFrame)
head(myDataFrame)
tail(myDataFrame)
str(myDataFrame)
class(myDataFrame$Gender)
myDataFrame$Gender <- as.factor(myDataFrame$Gender)
class(myDataFrame$Gender)
str(myDataFrame)



# Column
myDataFrame$Age
myDataFrame[2]
myDataFrame[c("Age")]
myDataFrame[2:3]
myDataFrame[c("Age","Gender")]
# Rows
myDataFrame[2,]

# Combined
myDataFrame[2:3,c("Age")]
myDataFrame[2:3,2:3]

#Levels

myDataFrame$Gender
table(myDataFrame$Gender)
table(myDataFrame$Age)
table(myDataFrame$Age, myDataFrame$Gender)

# Filtering

myDataFrame[myDataFrame$Gender == "1",]


# Ordering

myDataFrame[order(myDataFrame$Age),]
myDataFrame[order(-myDataFrame$Age),]

# Change Column Name
names(myDataFrame)[9] <- "Proudness_Level"
head(myDataFrame)
names(myDataFrame)[10] <- "Turn_Down_Other_Job_Likelihood"
head(myDataFrame)

#Changing Age for 3rd employee
myDataFrame[3,1] <- 36
head(myDataFrame)
#Changing Back 
myDataFrame$Age[3] <- 23
head(myDataFrame)


# Graphing
barplot(myDataFrame$Age)
barplot(myDataFrame$`Job Satisfaction`)
barplot(myDataFrame$Age, main = "Age of People", xlab = "People", ylab = "Age", col = "Blue")
pie(myDataFrame$Age)
pie(myDataFrame$Age, main = "Age of People")
stem(myDataFrame$Age)
hist(myDataFrame$Age)
boxplot(myDataFrame$Age)
boxplot(myDataFrame$Age,myDataFrame$Gender)

## Summary Stats

#Age
min(myDataFrame$Age)
max(myDataFrame$Age)
range(myDataFrame$Age)
StatRange = max(myDataFrame$Age) - min(myDataFrame$Age)
StatRange

mean(myDataFrame$Age)
sd(myDataFrame$Age)
var(myDataFrame$Age)
sqrt(var(myDataFrame$Age))
fivenum(myDataFrame$Age)
IQR(myDataFrame$Age)
quantile(myDataFrame$Age)
summary(myDataFrame$Age)
boxplot.stats(myDataFrame$Age)
boxplot.stats(myDataFrame$Age)$out


#Job Satisfaction
min(myDataFrame$`Job Satisfaction`)
max(myDataFrame$`Job Satisfaction`)
range(myDataFrame$`Job Satisfaction`)
StatRange = max(myDataFrame$`Job Satisfaction`) - min(myDataFrame$`Job Satisfaction`)
StatRange

mean(myDataFrame$`Job Satisfaction`)
sd(myDataFrame$`Job Satisfaction`)
var(myDataFrame$`Job Satisfaction`)
sqrt(var(myDataFrame$`Job Satisfaction`))
fivenum(myDataFrame$`Job Satisfaction`)
IQR(myDataFrame$`Job Satisfaction`)
quantile(myDataFrame$`Job Satisfaction`)
summary(myDataFrame$`Job Satisfaction`)
boxplot.stats(myDataFrame$`Job Satisfaction`)
boxplot.stats(myDataFrame$`Job Satisfaction`)$out



# Data Frame Summary

summary(myDataFrame)

#Age
by(myDataFrame$Age,myDataFrame$Gender,mean)
by(myDataFrame$Age,myDataFrame$Gender,sd)
by(myDataFrame$Age,myDataFrame$Gender,summary)

aggregate(myDataFrame$Age,list("Type" = myDataFrame$Gender),mean)
aggregate(myDataFrame$Age,list("Type" = myDataFrame$Gender),summary)


#Job Satisfaction
by(myDataFrame$'Job Satisfaction',myDataFrame$Gender,mean)
by(myDataFrame$'Job Satisfaction',myDataFrame$Gender,median)
by(myDataFrame$'Job Satisfaction',myDataFrame$Gender,summary)

aggregate(myDataFrame$Age,list("Type" = myDataFrame$Gender),median)
aggregate(myDataFrame$Age,list("Type" = myDataFrame$Gender),summary)




